services:
  db:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Tokyo

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - db
